#!/usr/bin/env python3
"""
Generate a minimal LVGL 9.x bitmap font from a TTF.

Emits a .c file with the same structure lv_font_conv would produce, but
covering only the characters the digital clock actually renders. Keeps
flash cost down to ~10-15 KB at 96 px while still letting us call it via
the existing `lv_font_t *` font slot.

Tuned for the t-watch-ultra-clock project — uses Montserrat-Medium.ttf
shipped with the LVGL library, 4 bits per pixel, no compression.
"""

import sys
import freetype

# ---- inputs ----------------------------------------------------------------

TTF_PATH = "/home/adobeflash/Downloads/twatch-ultra-clock/.pio/libdeps/twatch_ultra/lvgl/scripts/built_in_font/Montserrat-Medium.ttf"
SIZE_PX  = 96
BPP      = 4
OUT_PATH = "/home/adobeflash/Downloads/twatch-ultra-clock/src/lv_font_montserrat_clock_96.c"
FONT_VAR = "lv_font_montserrat_clock_96"

# Characters the clock actually needs: digits, colon, space, A/M/P.
# Sorted by codepoint so the cmap can use a single contiguous range
# trick for digits+colon (0x20, 0x30-0x3A, 0x41, 0x4D, 0x50). We use
# a sparse cmap to cover all of them cleanly with no extra glyphs.
CHARS = " 0123456789:AMP"

# ---- helpers ---------------------------------------------------------------

face = freetype.Face(TTF_PATH)
face.set_pixel_sizes(0, SIZE_PX)

# Render each glyph + collect metrics.
glyphs = []     # list of dicts {codepoint, adv_w, box_w, box_h, ofs_x, ofs_y, bitmap (bytes)}
for ch in CHARS:
    codepoint = ord(ch)
    face.load_char(ch, freetype.FT_LOAD_RENDER | freetype.FT_LOAD_TARGET_NORMAL)
    g = face.glyph
    bm = g.bitmap
    # FreeType returns metrics in 26.6 fixed point. LVGL stores adv_w in 1/16 px,
    # so divide by 4 (=64/16) to convert.
    adv_w = (g.metrics.horiAdvance + 2) // 4

    # Convert grayscale 8bpp → 4bpp (15 levels). Use perceptually flat
    # quantization: (v * 15 + 127) / 255 — same rounding lv_font_conv uses.
    w, h = bm.width, bm.rows
    pitch = bm.pitch
    pixels = []
    for y in range(h):
        row = bm.buffer[y*pitch:(y+1)*pitch]
        for x in range(w):
            v8 = row[x]
            v4 = (v8 * 15 + 127) // 255
            pixels.append(v4 & 0x0F)

    # Pack nibbles: pixel 0 → high nibble of byte 0, pixel 1 → low, etc.
    packed = bytearray()
    for i in range(0, len(pixels), 2):
        hi = pixels[i] << 4
        lo = pixels[i+1] if i + 1 < len(pixels) else 0
        packed.append(hi | lo)

    glyphs.append({
        "ch":         ch,
        "codepoint":  codepoint,
        "adv_w":      int(adv_w),
        "box_w":      int(w),
        "box_h":      int(h),
        "ofs_x":      int(g.bitmap_left),
        # LVGL's ofs_y is the offset from the baseline to the bottom of
        # the bitmap. FreeType's bitmap_top is from the baseline to the
        # top of the bitmap. Convert: ofs_y = bitmap_top - box_h.
        "ofs_y":      int(g.bitmap_top - h),
        "bitmap":     bytes(packed),
    })

# Stable insertion order — by codepoint so cmaps are simple.
glyphs.sort(key=lambda g: g["codepoint"])

# Compute bitmap_index for each glyph (running byte offset).
bitmap_index = 0
for g in glyphs:
    g["bitmap_index"] = bitmap_index
    bitmap_index += len(g["bitmap"])

# Font-wide metrics — line height & ascender/descender from face metrics
# (also 26.6 FP, also converted to pixels).
size_metrics = face.size
line_height  = (size_metrics.height + 32) >> 6
ascender     = (size_metrics.ascender + 32) >> 6
descender    = (-size_metrics.descender + 32) >> 6
# LVGL's base_line is descent (pixels below baseline that still belong to glyphs).
base_line    = descender

# ---- emit C ---------------------------------------------------------------

def fmt_bytes_per_line(data, n=12, indent="    "):
    out = []
    for i in range(0, len(data), n):
        chunk = data[i:i+n]
        out.append(indent + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    return "\n".join(out)

# Glyph 0 is reserved (placeholder for "not found"); real glyphs start at id=1.
# A sparse cmap is the simplest correct path for our scattered set: one
# big unicode_list with per-glyph offsets, glyph_id_start=1.
unicode_list = [g["codepoint"] for g in glyphs]
glyph_id_list = list(range(1, len(glyphs) + 1))

with open(OUT_PATH, "w") as f:
    f.write(f"""/*
 * Custom Montserrat {SIZE_PX} px subset font for the home-screen digital
 * clock. Generated by tools/gen_clock_font.py from Montserrat-Medium.ttf.
 *
 * Only includes the glyphs the clock actually uses (digits, colon,
 * space, A/M/P) so the flash cost stays tiny (~{(bitmap_index/1024):.1f} KB
 * of glyph bitmap data) compared with a full-character font at this size.
 *
 * The format mirrors what `lv_font_conv` produces — same struct layout,
 * cmap type, glyph descriptor field order — so this file plugs in via
 * the existing `lv_font_t *` slot exactly like the built-in fonts.
 */

#include "lvgl.h"

/*-----------------
 *    BITMAPS
 *----------------*/

static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {{
""")
    for g in glyphs:
        f.write(f"    /* U+{g['codepoint']:04X} \"{g['ch']}\" */\n")
        if g["bitmap"]:
            f.write(fmt_bytes_per_line(g["bitmap"]) + "\n")
        f.write("\n")
    f.write("};\n\n")

    f.write("""/*---------------------
 *  GLYPH DESCRIPTION
 *--------------------*/

static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {
    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0} /* id = 0 reserved */,
""")
    for g in glyphs:
        f.write(
            f"    {{.bitmap_index = {g['bitmap_index']}, "
            f".adv_w = {g['adv_w']}, "
            f".box_w = {g['box_w']}, "
            f".box_h = {g['box_h']}, "
            f".ofs_x = {g['ofs_x']}, "
            f".ofs_y = {g['ofs_y']}}},\n"
        )
    f.write("};\n\n")

    f.write("/*---------------------\n *  CHARACTER MAPPING\n *--------------------*/\n\n")
    f.write("static const uint16_t unicode_list[] = {\n    ")
    f.write(", ".join(f"0x{cp - unicode_list[0]:04X}" for cp in unicode_list))
    f.write("\n};\n\n")
    f.write("""static const lv_font_fmt_txt_cmap_t cmaps[] = {
    {
""")
    f.write(f"        .range_start = {unicode_list[0]}, ")
    f.write(f".range_length = {unicode_list[-1] - unicode_list[0] + 1}, ")
    f.write(f".glyph_id_start = 1,\n")
    f.write(f"        .unicode_list = unicode_list, .glyph_id_ofs_list = NULL, ")
    f.write(f".list_length = {len(unicode_list)}, ")
    f.write(f".type = LV_FONT_FMT_TXT_CMAP_SPARSE_TINY\n    }}\n}};\n\n")

    f.write(f"""/*--------------------
 *  ALL CUSTOM DATA
 *--------------------*/

static const lv_font_fmt_txt_dsc_t font_dsc = {{
    .glyph_bitmap = glyph_bitmap,
    .glyph_dsc = glyph_dsc,
    .cmaps = cmaps,
    .kern_dsc = NULL,
    .kern_scale = 0,
    .cmap_num = 1,
    .bpp = {BPP},
    .kern_classes = 0,
    .bitmap_format = 0,
}};

/*-----------------
 *  PUBLIC FONT
 *----------------*/

const lv_font_t {FONT_VAR} = {{
    .get_glyph_dsc    = lv_font_get_glyph_dsc_fmt_txt,
    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,
    .line_height = {line_height},
    .base_line = {base_line},
    .subpx = LV_FONT_SUBPX_NONE,
    .underline_position = -8,
    .underline_thickness = 4,
    .dsc = &font_dsc,
}};
""")

print(f"wrote {OUT_PATH}")
print(f"  {len(glyphs)} glyphs, bitmap = {bitmap_index} bytes")
print(f"  line_height = {line_height}, base_line = {base_line}, adv_w '0' = ", end="")
for g in glyphs:
    if g['ch'] == '0':
        print(f"{g['adv_w']/16:.2f} px")
        break
